---
title: "CCLHDME R Introduction"
output: 
  html_document:
    theme: sandstone
    toc: true
    toc_depth: 2
    toc_float: false
date: "2022-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  h1 {font-size: 30px;}
  h2 {font-size: 26px;}
  h3 {font-size: 20px;}
  p  {font-size: 16px;}
  li {font-size: 16px; margin: 2px 2px;}
  li p {margin: 2px 2px;}
  ul {font-size: 16px;}
  a  {color: blue;}
</style>


<br>

# Introduction

This document serves as a very general guide and tool for the CCLHDME R Workshop. And it provide a way to share learning materials and other resources.

The learning approach here is live demonstrations, with participants then doing the same steps live, as possible. Or just watching, and looking at the materials later. There are many different approaches, resources, styles, and preferance for learning R (or anything?).

# Workshop materials

not essential but helpful....

1. Download R_CCLHDME.zip from email and unzip in folder of your choosing, OR
2. Go to this [GitHub repo](https://github.com/mcSamuelDataSci/CCLHDME_R), click on "Code" (green button), download zip folder, and unzip in folder of your choosing, OR
3. Go to (Michael's Google drive) and download all files to folder of your choosing

pause....  


# About R and RStudio

**R** is an open source programming language for data processing, data visualization, and statistical computing.

**RStudio** is a free, open source tool that "sits on top" of R, and makes it easier and more efficient to use in all sorts of ways. Technically R Studio is an integrated development environment (IDE), that is organized so that users can clearly view graphs, data tables, R code, and outputs all at the same time. 

# Since R is open source is it safe to use? What about our IT department's concerns?

* all software has security issues
* the teams that oversee R (CRAN and RStudio) both review and test everything before it goes public and have large incentives for security
  * R and R Package Security [FAQ](https://support.rstudio.com/hc/en-us/articles/360042593974-R-and-R-Package-Security) for users or admins 
* May consider only installing "official" packages from "CRAN" rather than other "local" locations like on GitHub
* At CDPH R and R Studio are approved, available, and widely used with both the "free" desktop versions and the enterprise, server-based version

# Concepts in this session 

* Installing and loading R and R Studio

* R Studio console
* Using R as a calculator - mathematical operators
* R script files ("programming in R")
* Simple data objects in R
* Math with simple objects 
* Internal functions
  * arguments
  * "help" documentation
* Base R          ?
  * charts        ?
* Reading data
* Looking at data
  * Common functions

* Installing and loading packages
* Tidyverse
  * data wrangling
    * dplyr and pipe
    * joins
  * ggplot2
* Using an R Project ??????
* Thousands of other packages
  * summarytools  - easy frequencies, "cross-tables", and summary of a data.frame
  * outbreaks - line-listed data from a bunch of real outbreaks
  * epikit or epitools or something else 
 

<hr><br>



# Selected learning resources for R and R for epidemiology

* Hadley Wickham R for Data Science book
  * https://r4ds.had.co.nz/

* Applied Epi
  * Home: https://appliedepi.org/
  * The Epidemiologist R Handbook:  https://www.epirhandbook.com/en/
  * Free self-paced tutorial series: https://appliedepi.org/tutorial/
    * need free account 
    * basics:  https://tutorials.appliedepi.org/app/basics
    * data preparation
    * data cleaning
    * basics of data visualization in R
    * summary tables


* CCLHDME 2019 workshop

* R Studio cheat sheets:  https://www.rstudio.com/resources/cheatsheets/
  * [dply - data wrangling cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)

* Google

* YouTube

* Stackoverflow

* https://community.rstudio.com/




<br>
<hr>


# Installing R and R Studio

<br>

Download R from the [r-project](https://cloud.r-project.org/);  download the latest version suitable for your computer.



Download RStudio from [R Studio](https://www.rstudio.com/products/rstudio/download/#download) ;download the latest free Desktop version of RStudio suitable for your computer.


If needed, for more instructions on how to install R and RStudio click [here](https://rstudio-education.github.io/hopr/starting.html).

<br>

@ Workshop files

* Files in ??? S Studio pane

* "CCLHDME_R.Rproj"

<br>


@ rstudio screen shot here

* Code
* Console
* Environment (plus)
* Plots, Files, Help, Packages (plus)

<br>

@ script 1 (console and script)

* operators 
* objects
  * vectors

<br>

@ script 2 (console, then in script file)
  
* R packages
* read data
* examine data

<br>

@ script 3 

* install more  packages
* wrangle some data
* ggplot some data

<br>

# Concepts for possible future sessions

* options for installing packages
* working with paths and folders
* data type precedence
* Rules and best practices for naming objects
* more R object types
  *  data.frames and tibbles
  *  lists 
  *  class()
* sub-setting/indexing
* User built functions
* R markdown
  * https://skylab.cdph.ca.gov/communityBurden/_w_21945fed/xMDA/2020_Excess_Mortality.html
* ifelse() and other logical evaluation
* tables
* advanced data manipulation
* epidemiologic statistics and modeling
* shiny
* GIS
* shiny with GIS
* thousands of other packages
  * reading data
    * EXCELL
     * SAS  
  * Shiny - interactive visualizations and web sites
  * visual display
  * epidemiology
  * disease surveillance
  * outbreaks
  * GIS
    * tmap()
  * data analysis and modeling
  * tables
* GIT
* apply and loops


<!-- ```{r} -->
<!-- height <- rnorm(n=100, mean= 60, sd = 6) -->
<!-- weight <- height*1.2 +  rnorm(n=100, mean= 10, sd = 6) -->
<!-- hist(height, breaks=50) -->
<!-- plot(height, weight) -->
<!-- ``` -->


